# Generated by Django 4.1 on 2022-08-22 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_coin_p2porder_alter_payment_fiat_delete_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2porder',
            name='parsing_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 21, 13, 58, 748444)),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('name', 'fiat')},
        ),
    ]
