# Generated by Django 4.1 on 2022-09-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='figi',
            field=models.CharField(default='000000', max_length=20),
        ),
        migrations.AddField(
            model_name='currencies',
            name='name',
            field=models.CharField(default='USDRUB', max_length=10),
        ),
    ]
