# Generated by Django 4.1 on 2022-09-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_currencies_figi_currencies_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=20)),
                ('money_amount', models.IntegerField()),
                ('spread', models.FloatField()),
                ('is_subscribed', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Currencies',
            new_name='Currency',
        ),
    ]
