# Generated by Django 4.1 on 2022-09-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_user_is_logged_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20)),
                ('link', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
