# Generated by Django 4.1 on 2022-09-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2porder',
            name='lower_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='upper_limit',
            field=models.FloatField(default=0.0),
        ),
    ]
