# Generated by Django 4.1 on 2022-09-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_p2porder_lower_limit_p2porder_upper_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_text', models.TextField()),
                ('spread', models.FloatField()),
                ('lower_limit', models.FloatField()),
                ('upper_limit', models.FloatField()),
            ],
        ),
    ]
