# Generated by Django 4.1 on 2022-09-08 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_circle'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='creating_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
