# Generated by Django 4.1 on 2022-09-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_circle_creating_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='variant',
            field=models.IntegerField(default=0),
        ),
    ]
