# Generated by Django 4.1 on 2022-09-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_circle_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestchangePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('bestchange_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BestchangeExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('min_sum', models.FloatField()),
                ('max_sum', models.FloatField()),
                ('exchanger_name', models.CharField(max_length=40)),
                ('payment_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_payment_from', to='data.bestchangepayment')),
                ('payment_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_payment_to', to='data.bestchangepayment')),
            ],
        ),
    ]
