# Generated by Django 4.1 on 2022-09-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_bestchangepayment_bestchangeexchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestchangeexchange',
            name='payment_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_from', to='data.bestchangepayment'),
        ),
        migrations.AlterField(
            model_name='bestchangeexchange',
            name='payment_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_to', to='data.bestchangepayment'),
        ),
    ]
