# Generated by Django 4.1 on 2022-09-10 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_bestchangeexchange_payment_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestchangeexchange',
            name='parsing_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
