# Generated by Django 4.1 on 2022-09-10 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_cryptocurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('parsing_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.coin')),
                ('cryptocurrency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.cryptocurrency')),
            ],
        ),
    ]
