# Generated by Django 4.1 on 2022-09-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_binancespot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binancespot',
            old_name='rate',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='binancespot',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='binancespot',
            name='cryptocurrency',
        ),
        migrations.AddField(
            model_name='binancespot',
            name='symbol',
            field=models.CharField(default='', max_length=20),
        ),
    ]
