# Generated by Django 4.1 on 2022-09-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_rename_rate_binancespot_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BinanceSpot',
            new_name='BinanceSpotPrice',
        ),
    ]
