# Generated by Django 4.1 on 2022-12-23 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_rename_binancespot_binancespotprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_signal_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
